### ISSUE TITLE
Error: Cannot find module 'lodash/pickBy'

### ISSUE THREAD

**Issue by chrisfisher** [adamgibbons/ics#154]
I get this error after upgrading to 2.23.0: `Error: Cannot find module 'lodash/pickBy'`

Presumably related to https://github.com/adamgibbons/ics/pull/150?

```
"trace": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lodash/pickBy'",
        "Require stack:",
        "- /var/task/node_modules/ics/dist/pipeline/build.js",
        "- /var/task/node_modules/ics/dist/pipeline/index.js",
        "- /var/task/node_modules/ics/dist/index.js",
        "- /var/task/node_modules/ics/index.js",
```

**Comment by adamgibbons** [comment]
Should be fixed by https://github.com/adamgibbons/ics/commit/f031719add4fa95c787ceae57ac4e9eb501a46c6

**Comment by devnoot** [comment]
I'm running into this issue as well. 

From my `package.json`

```
  "dependencies": {
    "ics": "^2.26.1"
  }
````

**Comment by devnoot** [comment]
FYI: I was able to work around the issue by going into `node_modules/ics` and running `npm install`

**Comment by tobiasso85** [comment]
error still present with:
`"ics": "^2.26.1",`
