### PR TITLE
Replace lodash/pickBy in pipeline/build.js

### LINKED ISSUE #154: Error: Cannot find module 'lodash/pickBy'
I get this error after upgrading to 2.23.0: `Error: Cannot find module 'lodash/pickBy'`

Presumably related to https://github.com/adamgibbons/ics/pull/150?

```
"trace": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lodash/pickBy'",
        "Require stack:",
        "- /var/task/node_modules/ics/dist/pipeline/build.js",
        "- /var/task/node_modules/ics/dist/pipeline/index.js",
        "- /var/task/node_modules/ics/dist/index.js",
        "- /var/task/node_modules/ics/index.js",
```

### PR DESCRIPTION
**Pull request by egs33**
lodash is removed in #150. But it is used in `pipeline/build.js`.
lodash is replaced by js native functions in this PR.

This PR resolves #154.

### CODE REVIEW

**Comment by adamgibbons** [comment]
Thank you!
